name = "illinihunt-reverse-proxy"
main = "cloudflare-worker.js"
compatibility_date = "2024-10-01"
account_id = "e64cab2cda0c00bba0784e6cd56e36c6"

# Routes for illinihunt.org domain
routes = [
  { pattern = "illinihunt.org/*", zone_name = "illinihunt.org" },
  { pattern = "*.illinihunt.org/*", zone_name = "illinihunt.org" }
]
